### ISSUE TITLE
Wiggling motion when I start Gazebo

### ISSUE THREAD

**Issue by Toprak-Efe** [Ozyegin-Planetary-Robotics-Laboratory/Ares-Arm-Simulation#1]
Possible problem with physics, I do not know why this happens for this specific case, maybe it is the null collision shapes (The collision shapes you have created that have dimensions 0,0 might still be checked for collisions, considering these two parameters they might be colliding with themselves). The end result is the gif below.
![Peek 2023-12-08 15-51](https://github.com/Ozyegin-Planetary-Robotics-Laboratory/Ares-Arm-Simulation/assets/118849654/3d71d031-45cb-4b5f-b45a-c924fff9aa10)
Fix the collision problem, check if the motor interface is actually functional afterwards. It is nice work that you have done, though it is unfinished. Test your work so I won't have to do it in your place.

**Comment by threos** [comment]
I believe this is solved @sedenmutaf1

**Comment by sedenmutaf1** [comment]
> I believe this is solved @sedenmutaf1 

Yes,but this is an old problem that we solved on the previous model.New model doesn't have any wiggling bug.If there is any other bug you see,I'll try to fix it as quickly as I can.

**Comment by Toprak-Efe** [comment]
This problem was fixed, start a new issue.
